# Generated by Django 6.0.5 on 2026-06-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('clave', models.CharField(blank=True, max_length=50)),
                ('pais', models.CharField(default='Ecuador', max_length=50)),
                ('anio', models.CharField(max_length=4)),
                ('tipo_vehiculo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('placas', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=20)),
                ('alin_automovil', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('alin_camioneta', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('alin_furgoneta', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('alin_camion', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('bal_automovil', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('bal_camioneta', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('bal_furgoneta', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('bal_camion', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('combo_automovil', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('combo_camioneta', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('combo_furgoneta', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('combo_camion', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('enllantaje', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('nitrogeno', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('parches', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('corr_del_izq', models.CharField(blank=True, max_length=100)),
                ('corr_del_der', models.CharField(blank=True, max_length=100)),
                ('corr_post_izq', models.CharField(blank=True, max_length=100)),
                ('corr_post_der', models.CharField(blank=True, max_length=100)),
                ('otros', models.TextField(blank=True)),
                ('llamadas', models.CharField(blank=True, max_length=100)),
                ('valor_transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
