# Generated by Django 6.0.5 on 2026-06-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_alin_automovil_ordentrabajo_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordentrabajo',
            old_name='total',
            new_name='alin_automovil',
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='alin_camion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='alin_camioneta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='alin_furgoneta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='anio',
            field=models.CharField(default=2026, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='bal_automovil',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='bal_camion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='bal_camioneta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='bal_furgoneta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='clave',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='color',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='combo_automovil',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='combo_camion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='combo_camioneta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='combo_furgoneta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='corr_del_der',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='corr_del_izq',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='corr_post_der',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='corr_post_izq',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='enllantaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='llamadas',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='nitrogeno',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='pais',
            field=models.CharField(default='Ecuador', max_length=50),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='parches',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='valor_transferencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='numero_orden',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
